### ISSUE TITLE
Importing module is slow

### ISSUE THREAD

**Issue by BlueDrink9** [PowershellFrameworkCollective/PSUtil#57]
If I import the module in my profile, it adds around 3 seconds to my startup time - 50%. Fairly annoying, and much more than other plugins.

Is there a way to lazy-load the heavier content of the module?

**Comment by FriedrichWeinmann** [comment]
Heya, unfortunately there is not.
You can defer import to automatic import when you start using the module, but that's problematic, since many features of the module do not trigger auto-import and some that usually do, don't since they overlap builtin utilities (e.g. `replace`).

The Module depends on the PSFramework module, so you're importing two modules.
I can't say it usually takes 3 seconds on my machine (I'm on ~1.5s for the two modules) though. Did you install it them from the gallery or download from the github repo?
The github repo variant is not optimized for import speed (optimization is part of the build sequence).

Also note: If you use PSUtil for its strings commands only:
The `string` module is a standalone module that has the string commands in an optimized way and is a lot leaner.

**Comment by BlueDrink9** [comment]
From gallery.

I have a plugin function that tries to import the module, then installs it from gallery if it isn't found. That might add a tiny amount of extra time, but not enough to account for this.

I was using ZLocation as the only plugin loaded as well, because it provides profile load timing.

**Comment by FriedrichWeinmann** [comment]
Out of curiosity: What _do_ you use here?

**Comment by BlueDrink9** [comment]
Currently, grep, exp, explorer, and an assumption that other things I try will magically work. I decided to install this after reading the readme and feeling like the thinking was in line with my own.

**Comment by FriedrichWeinmann** [comment]
Glad you like it for what it does :)
I'll do some profiling later when I get back to the hotel.
Do you have the system specs? SSD or HDD?

**Comment by BlueDrink9** [comment]
SSD, no other real speed complaints using powershell or windows in general. 

Single test, doing nothing in profile except loading PSUtil and ZLocation takes 3600 ms. Without PSUtil, 960 ms.

I have clink installed, but afaik it doesn't affect powershell, only cmd.

**Comment by FriedrichWeinmann** [comment]
One last thing:
Can you test on your machine the delta when you only load PSFramework (the module PSUtil depends on) instead?
That would help me figure out where to start looking for the bottleneck

**Comment by FriedrichWeinmann** [comment]
```text
PS C:\> Measure-Command { Import-Module PSFramework }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 274
Ticks             : 12748791
TotalDays         : 1.47555451388889E-05
TotalHours        : 0.000354133083333333
TotalMinutes      : 0.021247985
TotalSeconds      : 1.2748791
TotalMilliseconds : 1274.8791



PS C:\> Measure-Command { Import-Module PSUtil }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 225
Ticks             : 2256345
TotalDays         : 2.61151041666667E-06
TotalHours        : 6.267625E-05
TotalMinutes      : 0.003760575
TotalSeconds      : 0.2256345
TotalMilliseconds : 225.6345
```
On my machine it's definitely spending most of its time on PSFramework (which is expected, since it is way larger).

If you want to rebuild and take the things you like from PSUtil, be warned: Much of it depends on PSFramework and if the same ratio holds true for you, odds are you'll need to spend quite a bit of effort on making that happen (e.g. the configuration options or dynamic tab completion - such as the property completion on EXP - are implemented in PSFramework).
